query GetTimesheets($userId: String, $withTotalHours: Boolean) {
  getTimesheets(userId: $userId, withTotalHours: $withTotalHours) {
    id
    userId
    orgId
    startDate
    endDate
    state
    submittedOn
    approvedOn
    updatedBy
    updatedOn
    totalDuration
  }
}
