query GetDurationTimeRecords($startTime: DateTime, $endTime: DateTime, $userId: String) {
  getDurationTimeRecords(startTime: $startTime, endTime: $endTime, userId: $userId) {
    id
    startTime
    endTime
    taskName
    description
    tags
    projectId
    isBillable
    userId
    timesheetId
  }
}
