query GetTimeRecords($userId: String) {
  getTimeRecords(userId: $userId) {
    id
    startTime
    endTime
    taskName
    description
    tags
    projectId
    isBillable
    userId
    timesheetId
  }
}
