query GetTimesheets($userId: String) {
  getTimesheets(userId: $userId) {
    id
    userId
    orgId
    startDate
    endDate
    state
    submittedOn
    approvedOn
    updatedBy
    updatedOn
    totalDuration
  }
}
