fragment TimeRecord on TimeRecord {
    id
    startTime
    endTime
    taskId
    taskName
    description
    tags
    isBillable
    projectId
    clientId
    userId
    orgId
    timesheetId
    editable
}