query GetScheduleEvents($userId: String) {
 	getScheduleEvents(userId: $userId) {
        id
        title
        allDay
        start
        end
        desc
        resourceId
        tooltip
    }
}